In [ ]:
# Numpy - in principal o librarie (de matematica), care in principal ne ajuta prin a avea acces la np.array .

# Diferente intre np.array si liste in python:
# 1. Libraria numpy ne permite diferite operatii matematice pe siruri pe care listele normale nu ni le ar fi permis: arr.sum(), putem aduna 2 np arrays piecewise, puitem sa inmultim rapid matrici cu ele etc.
# 2. Operatiile pe numpy arrays sunt paralelizabile, iar listele obisnuite

In [ ]:
import numpy as np

classic_array = [1, 2, 3, 4, 5]
arr_1d = np.array([1, 2, 3, 4, 5])

In [ ]:
classic_array

[1, 2, 3, 4, 5]

In [ ]:
print(arr_1d)

[1 2 3 4 5]


In [ ]:
classic_array * 2

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

In [ ]:
arr_1d * 2

array([ 2,  4,  6,  8, 10])

In [ ]:
arr_2d = np.array( [ [1.0, 2.0, 3.0], [4.0, 5.0, 6.0] ] )

In [ ]:
print(arr_2d)

[[1. 2. 3.]
 [4. 5. 6.]]


In [ ]:
# Built-in initialization functions

zeros = np.zeros((3, 3), dtype=np.int32)
ones = np.ones((2, 4), dtype=np.float64)
range_arr = np.arange(0, 10, 2)
linear_space = np.linspace(-2, 5, 11)
random_arr = np.random.default_rng(41).standard_normal((3, 2))

In [ ]:
# Properties

print(f'Shape: {arr_2d.shape}')
print(f'Dimensions: {arr_2d.ndim}')
print(f'Data type: {arr_2d.dtype}')

total_el = arr_2d.shape[0] * arr_2d.shape[1]
# total_el = arr_2d.size
print(f'Total elements: {total_el}')
print(f'Item size (bytes): {arr_2d.itemsize}')

Shape: (2, 3)
Dimensions: 2
Data type: float64
Total elements: 6
Item size: 8


In [ ]:
# Indexing, slicing and reshaping

matrix = np.array([[10, 20, 30, 40], [50, 60, 70, 80], [90, 100, 110, 120]])

# Slicing
row_1 = matrix[1, :]
col_2 = matrix[:, 2]

# Submatrix with rows 0-1 si columns 1-2
sub_matrix = matrix[0:2 , 1:3]

In [ ]:
# Masking / filters

mask = ( matrix > 50 ) & ( matrix < 100 )
filtered_values = matrix[mask]

In [ ]:
# Reshaping and transposing

flat = np.arange(12) # [0, ...., 11]
grid = flat.reshape(3, 4)

transposed = grid.T

In [ ]:
grid.shape

(3, 4)

In [ ]:
transposed.shape

(4, 3)

In [ ]:
grid

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
flattened_view = grid.ravel() # asta doar face view

In [ ]:
flattened_view

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [ ]:
flattened_copy = grid.flatten()

In [ ]:
# Operations

A = np.array([ [1, 2, 3], [4, 5, 6] ]) # A.shape = (2, 3)
B = np.array([10, 20, 30]) # B.shape = (3, )

addition = A + B

In [ ]:
addition

array([[11, 22, 33],
       [14, 25, 36]])

In [ ]:
scalar_multiplication = A * 2
scalar_multiplication

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [ ]:
sqrt_vals = np.sqrt(A)
sqrt_vals

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [ ]:
# Reduction & Aggregations
# axis = 0 -> along columns
# axis = 1 - > along rows

col_sums = A.sum(axis = 0)
print(col_sums)
print(col_sums.shape) # (3, )

[5 7 9]
(3,)


In [ ]:
A = np.array([ [1, 2, 3], [4, 5, 6] ]) # A.shape = (2, 3)
row_means = A.mean(axis = 1)
print(row_means) # [2.0, 5.0]
print(row_means.shape) # (2, )

[2. 5.]
(2,)


In [ ]:
std_dev = A.std()
std_dev

np.float64(1.707825127659933)

In [ ]:
arg_max_idx = A.argmax(axis = 1) # Indices of maximum values per row
arg_max_idx

array([2, 2])

In [ ]:
# Problem: Se da unf feature matrix X de shape (N, D) . Fa StandardScaler pe matricea aceasta astfel incat fiecare coloana sa aiba o medie de 0 si o deviatie standard de 1

def StandardScaler(X):
  mean = np.mean(X, axis = 0)
  std = np.std(X, axis = 0)

  return (X - mean) / std


data = np.array([ [10.0, 20.0], [20.0, 400.0], [30.0, 600.0] ])
normalized_data = StandardScaler(data)

In [ ]:
normalized_data

array([[-1.22474487, -1.33025759],
       [ 0.        ,  0.2494233 ],
       [ 1.22474487,  1.08083429]])